name: pub_server
version: 0.1.2-dev
author: Dart Team <misc@dartlang.org>
description: A Dart package containing re-usable components for making a pub package server.
homepage: https://github.com/dart-lang/pub_server

environment:
  sdk: '>=1.5.0 <2.0.0'

dependencies:
  logging: ">=0.9.3 <1.0.0"
  mime: ">=0.9.3 <0.10.0"
  pub_semver: ">=1.1.0 <1.3.0"
  shelf: ">=0.5.6 <0.7.0"
  yaml: ">=2.1.2 <3.0.0"

dev_dependencies:
  archive: ">=1.0.0 <2.0.0"
  args: ">=0.12.2 <0.14.0"
  http: ">0.11.0 <0.12.0"
  unittest: ">=0.11.4 <0.12.0"
