name: pub_server
version: 0.1.6-dev
author: Dart Team <misc@dartlang.org>
description: Re-usable components for creating a custom Dart package server.
homepage: https://github.com/dart-lang/pub_server

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  http_parser: ^3.0.0
  logging: ">=0.9.3 <1.0.0"
  mime: ">=0.9.3 <0.10.0"
  pub_semver: ^1.1.0
  shelf: ">=0.5.6 <0.8.0"
  yaml: ^2.1.2

dev_dependencies:
  archive: ">=1.0.0 <3.0.0"
  args: ^1.4.0
  http: ^0.12.0
  path: ^1.5.1
  pedantic: ^1.2.0
  test: ^1.3.0
